version: '3'
services:
  api_db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'

  api:
    image: api
    build: ./api
    environment:
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '5432'
      DB_HOST: api_db
    restart: on-failure
    depends_on:
      - api_db

  indexer_token:
    image: api
    build: ./api
    volumes:
      - data:/app/contracts
    environment:
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '5432'
      DB_HOST: api_db
    command: python3 indexer_token_sale.py
    restart: on-failure
    depends_on:
      - api_db

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -a 100 -e 100000

  hardhat:
    image: hardhat
    build: ./contracts
    volumes:
      - data:/usr/src/app

volumes:
  data:
  db:
